.circleci/config.yml

I called `ls dist` after `cd dist`. D'oh!

Circle config bugfix

---

Dockerfile

Use alpine docker image

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

v0.0.10 Release Candidate.

---

.circleci/config.yml
schema/echo.proto
schema/identity.proto
schema/messaging.proto
schema/testing.proto

Updates GAPIC config annotations per changes to input-contract.

update gapic config annotations

---

Dockerfile
util/cmd/release/main.go

fix retrieval of dependencies and installation of binary in release tool & Dockerfile

fix release tool

---

.circleci/config.yml

* strip v-prefix for image tag

change docker image tagging back to strip v-prefix

---

.circleci/config.yml

* renable gapic smoke tests requirements on release jobs
* bump kotlin & python gapic Docker image versions

renable smoke tests

---

server/identity_service.go
server/identity_service_test.go

Fix issue where deleted Users were getting tombstoned.

---

server/observer.go
server/observer_test.go
server/session.go
server/session_test.go
server/test.go

This PR includes implementation for the Test and Session resources.

Testing Sessions and Test Case Interface

---

server/services/operations_service_test.go

Forgot to add this test in #96

Add test for WaitOperation.

---

.circleci/config.yml
CHANGELOG.md
util/cmd/print_changes/main.go

I need to add more documentation on the usage of this script but that will come later this week while I'm documenting all the things.

Add script to place release changes on release

---

.circleci/config.yml
util/compile_protos.go

- Added a job regenerate to run on master which does the following
- Checks out the repo
- Calls compile_protos
- Check if theres a diff
- If theres a diff push to master

 Add CI to regenerate client, cmd, and server source if needed

---

nodejs-server/src/echoServer.ts

Double logging. The request is already logged in line 194. Removing extra logging.

fix: removing extra logging

---

.circleci/config.yml

chore: bump gapic-go image version

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
nodejs-server/README.md
util/cmd/bump_version/main.go

release v0.1.2

---

schema/google/showcase/v1beta1/echo.proto

Not sure if you want to complete the sentence or get rid of it (I just deleted it for now)

Half-sentence in comment

---

.circleci/config.yml

Not sure what the original problem was, but hopefully this is all it takes. 
[resolves #137]

Enable Kotlin smoke test

---

renovate.json

* go: run `go mod tidy` 
* nodejs: do not pin deps

chore: make renovate tidy go.mod & not pin deps

---

server/services/operations_service.go
server/services/operations_service_test.go

Very simple implementation of the remaining LRO methods.
Note that the LRO methods don't appear to be a part of the CLI and I did not attempt to add them.
[resolves #180]

Add dummy LRO service

---

README.md

chore: improve comments on insecure channel use

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

release v0.7.0

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

Release for fix #335
cc: @arithmetic1728

release v0.8.1

---

.circleci/config.yml
util/cmd/release/main.go

* update CI version of protoc to stable v3.12.0
* add --experimental_allow_proto3_optional to release script

chore: update CI protoc and release script

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

See CHANGELOG.md for details of changes included in the release.

release v0.10.0

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

See CHANGELOG for contents of the release.
cc @software-dov @xiaozhenliu-gg5

release v0.11.0

---

server/services/identity_service_test.go
server/services/messaging_service_test.go

chore: refactor email domain in test data

---

CHANGELOG.md
README.md
cmd/gapic-showcase/version.go
util/cmd/bump_version/main.go

See CHANGELOG for release notes.

release v0.12.0

---

.circleci/config.yml

(and in the interests of inclusive language, removed the use of "sanity-check")

chore: Add a CircleCI test to do a basic check on the REST server

---

schema/google/showcase/v1beta1/BUILD.bazel

fix: bazel proto rule issue

---

.github/workflows/release.yaml

chore: fix release asset version

---

go.mod
util/compile_protos.go

This enables generation of both GRPC and REST clients.

feat: generate both grpc and rest clients

---

README.md

chore: Update README to avoid showing Go warnings

---

schema/google/showcase/v1beta1/compliance.proto
schema/google/showcase/v1beta1/echo.proto
schema/google/showcase/v1beta1/identity.proto
schema/google/showcase/v1beta1/messaging.proto
schema/google/showcase/v1beta1/sequence.proto
schema/google/showcase/v1beta1/testing.proto

fix: ruby package name

---

go.mod
schema/google/showcase/v1beta1/showcase_v1beta1.yaml
server/genrest/genrest.go
server/genrest/operations.go
server/genrest/showcase-rest-sample-response.txt
util/genrest/protomodelcreator.go

chore(genrest): fix DeleteOperation binding, remove xerrors dep

---

README.md
util/cmd/release/main.go

Also do some copyediting fixes.

fix: Update README with latest version number

---

.github/workflows/assets.yaml

Follow up to https://github.com/googleapis/gapic-showcase/pull/1420

chore: Fix workflow typo and refactor to a single job

---

.github/workflows/assets.yaml

Follow up to: https://github.com/googleapis/gapic-showcase/pull/1421

chore: fix syntax to get upload url

---

.github/workflows/assets.yaml

Follow up to https://github.com/googleapis/gapic-showcase/pull/1423
Can't do conditional statements directly within the variable definition, so creating a separate job to determine it.

chore: fix workflow for upload url

---

.github/workflows/assets.yaml

Follow up to: https://github.com/googleapis/gapic-showcase/pull/1424
Not sure exactly why the output isn't saving correctly; renaming some things for clarity and added some logging

chore: fix workflow output

---

.github/workflows/assets.yaml

Follow up to https://github.com/googleapis/gapic-showcase/pull/1426

chore: remove extra quotation in workflow

---

.github/workflows/assets.yaml

I think this change should fix the error with needing to directly access the environment variable

chore: fix reference variable

---

schema/google/showcase/v1beta1/BUILD.bazel

Fixes https://github.com/googleapis/gapic-showcase/issues/1475
Let me know if we should block this PR on https://github.com/googleapis/gapic-showcase/issues/1476

fix: add missing dependency in bazel rule

---

renovate.json

chore: fix renovate JSON syntax

---

.github/workflows/assets.yaml
.github/workflows/ci.yaml
go.mod

chore: upgrade to go1.23

---

schema/google/showcase/v1beta1/echo.proto

The real purpose of this PR is to have a `fix` conventional commit that will trigger a release PR.

fix: tweak proto comments

---

.github/workflows/ci.yaml

ref: https://github.com/jbranchaud/til/blob/master/github-actions/capture-an-output-value-for-use-in-a-later-step.md
This should address #1577

fix: name code_suggester step to fix CI action
