googleapis/gapic-showcase

showcase.proto
It does not exist on `EchoRequest`.
=> Remove erroneous response_delay

schema/echo.proto
How about setting the `java_multiple_files` option since it's typically used?
=> Java multiple files

schema/echo.proto
The 0.5 release removed a field from the proto, but left it in the `method_signature` annotation.
=> fix flattening config

.circleci/config.yml, util/release/main.go
This moves the bulk of the release script to a go file. This also
changes the released binaries to become tarballs. This is for two
specific reasons:
1. By tarballing the executables, it preserves the +x permission on the
file.
1. It allows for simpler binary usage
```
curl -L <link to tar> | sudo tar -zx -- --directory /usr/local/bin/
gapic-showcase start
```
```
curl -L <link to binary>
chmod u+x binary
mv binary /usr/local/bin/gapic-showcase
gapic-showcase start
```
=> Move release script to a go file

.circleci/config.yml
Fixes #78 
* switches to use of `CIRCLE_TAG` instead of installing & running the `gapic-showcase` CLI to determine the version, because the affected jobs only run on tag pushes
* hard code github org & repo name
=> fixes for github_release job

README.md
The command we provide in the README for using Docker fails to publish port 7469 (preventing communication with Showcase).
=> Update README with correct Docker command.

.circleci/config.yml, README.md
* push image to project configured in CircleCI (changed it to `gapic-images` & added new credentials already)
* update README with new docker image name
=> move docker images to gapic-images

schema/messaging.proto
gapic-generator fails to generate clients for Showcase v0.0.13 because of these path templates that don't start with `/`.
```
ERROR: google/showcase/v1alpha3/messaging.proto:93:3: http: In path template 'v1alpha3/{parent=users/*/profile}/blurbs': effective path must start with leading '/'.
```
Fixing that (and will release v0.0.14 when fixed).
=> Fix path templates to start with /

schema/messaging.proto
One mismatched `}` breaks gapic-generator. Fixing that.
=> fixing path templates once more

schema/messaging.proto, schema/testing.proto
One more!
```
ERROR: google/showcase/v1alpha3/testing.proto:74:3: http: undefined field 'name' on message 'google.showcase.v1alpha3.ListTestsRequest'.
ERROR: google/showcase/v1alpha3/messaging.proto:172:3: http: undefined field 'parent' on message 'google.showcase.v1alpha3.StreamBlurbsRequest'.
```
@landrito Can you please take a look to check if my changes to path template are OK (feel free to update it if not). I'm not really sure that I used the right field names.
Thanks!
=> fix path template field names

util/cmd/bump_version/main.go
- Adds documentation to the script.
- Removes dependency on $GOPATH but the script must be ran on the root directory of the repo
- small renaming change
- adds a version regex for api version bumps to ensure they conform
- ensures that protos are in the correct directory
=> Update bump_version script

.circleci/config.yml, nodejs-server/.gitignore, nodejs-server/README.md, nodejs-server/package.json, nodejs-server/src/echoServer.ts, nodejs-server/src/index.ts, nodejs-server/src/operationsServer.ts, nodejs-server/test/fixtures/chat.in, nodejs-server/test/fixtures/collect.in, nodejs-server/test/fixtures/test.baseline, nodejs-server/test/test.sh, nodejs-server/tsconfig.json, nodejs-server/tslint.json
This PR adds a Node.js gRPC server that can serve RPCs defined in `echo.proto` (including long running operations). A trivial baseline test checks the basic functionality of the server.
Usage:
Start server:
```sh
$ npm install
$ node build/src/index.js --verbose    # will start on port 7469
```
Play with client:
```sh
$ docker run --rm --network host gcr.io/gapic-images/gapic-showcase:0.1.1 \
echo --address host.docker.internal:7469 echo --response content --response.content okay
$ docker run --rm --network host gcr.io/gapic-images/gapic-showcase:0.1.1 \
echo --address host.docker.internal:7469 wait --end ttl --end.ttl.seconds 5 \
--follow --response success --response.success.content okay
```
@JustinBeckwith This will be used in GAX testing. Asking you to review TypeScript stuff :) …
=> feat: Node.js gRPC server

.circleci/config.yml, .gitmodules, schema/google/showcase/v1beta1/identity.proto, schema/google/showcase/v1beta1/messaging.proto, schema/google/showcase/v1beta1/testing.proto
Updates resource annotations to use the latest resource.proto. This seems to break the smoke tests since presumably the base docker image of those tests do not yet support the protos.
=> Update resource annotations.

server/services/operations_service.go, server/services/operations_service_test.go
The token will cause clients to loop forever.
=> Remove next page token

schema/google/showcase/v1beta1/echo.proto, server/services/echo_service.go, server/services/echo_service_test.go
This adds the ability for all echo services to echo the contents of the `showcase-trailer` metadata key to the response trailers. This is useful to ensure that any gapic helper code doesn't obscure access to trailing metadata across all method types.
=> Echo headers -> trailers

go.mod, go.sum
* updates a broken dependency pseudo-version
* declares go version 1.13 in go.mod
=> chore: fix go.mod for 1.13

.circleci/config.yml, CHANGELOG.md, README.md, cmd/gapic-showcase/version.go, schema/google/showcase/v1beta1/messaging.proto, util/cmd/bump_version/main.go
It's of course a little bit of a breaking change, but do we care here? It's an internal test library.
=> fix: correct resource type for Blurb

util/compile_protos.go
Fixes #227 
CI is using Go 1.13 images, but still sets everything up in a `GOPATH`-type way. This is OK because the scripts can now be used locally with Go 1.13 to regen, print changes, etc.
=> chore: update compile_protos to not be GOPATH based

.circleci/config.yml
The CI scripts had not been updated in a while and were still using `go get` to install dependencies. This was also updating them in the same job, rather than respecting the `go.mod`. It creates regen PRs [like this](https://github.com/googleapis/gapic-showcase/pull/329) that update the `go.mod` and are using a newer version of `protoc-gen-go` than specified via `github.com/golang/protobuf` in the `go.mod`.
So we switch to `go mod download` to retrieve _build-time_ dependencies, and still use `go get` to retrieve generation-time dependencies (e.g. getting protoc-gen-go_gapic b.c it is not listed in the go.mod b.c it is not a build-time dependency for the server, client or cli).
In the case of `protoc-gen-go`, we want to respect the version of `github.com/golang/protobuf` specified in the …
=> chore: ensure go mod enabled in ci build

CHANGELOG.md, README.md, cmd/gapic-showcase/version.go, util/cmd/bump_version/main.go
See added section in `CHANGES.md` for changes in this release.
CC: @arithmetic1728 this releases the mtls server support you just added
=> release v0.8.0

cmd/gapic-showcase/run.go
I made a silly mistake, caught this problem when doing system tests.
=> fix: fix the typo in mtls logic

.circleci/config.yml
Run `go mod tidy` prior to opening a regeneration PR in order to prevent generation dependencies (e.g. gapic-generator-go) from being added as an indirect, like in [here](https://github.com/googleapis/gapic-showcase/pull/348/files#diff-37aff102a57d3d7b797f152915a6dc16R6).
Tested locally.
=> chore: tidy go.mod in regen PRs

.circleci/config.yml
Upgrade protoc version used in CI & for automated regen to latest prior to next release.
=> chore: bump CI protoc versrion

.circleci/config.yml, util/compile_protos.go
* Upgrade version of protoc used in CI to v3.12.0-rc1
* Add proto3_optional enablement flag to compile_protos
* Disable go_cli regen until it is updated to support proto3_optional until https://github.com/googleapis/gapic-generator-go/issues/378 is fixed and released
* This is OK b.c nothing is changing in the client library that would affect the CLI, and the main use case for the CLI is just running the server. Thus the small change in the API surface isn't as urgent as getting `optional` integrated with gapic-showcase
* When `optional` is integrated, a manual change to the CLI will be necessary b.c `optional` affects the code generated by `protoc-gen-go` and thus the `struct`s used by the CLI
=> chore: update regen tools for proto3_optional

util/compile_protos.go
https://github.com/googleapis/gapic-generator-go/issues/378 was closed and released in gapic-generator-go v0.14.1.
I tested everything locally, adding various uses of `optional` to verify the `go_cli` wouldn't generate a broken CLI.
CI should pull the latest release for generation and testing. This will show that it is backwards compatible. When a change is made to add `optional` to the showcase protos, we will need to include all new generated sources (pb.go, gapic and cli code) to properly test in CI.
=> chore: enable go_cli generation

README.md
- Repurpose `Go Environment` section for `Development Environment`
- Add `protoc` install step (because we will use `proto3_optional` we must have at minimum protoc v3.12.0) for development
- Add `api-common-protos` submodule init step
- Change `PATH` export to reference `go env GOPATH` output rather than hardcoded `~/go/bin`
cc: @xiaozhenliu-gg5 I hope this helps others in the future, thanks for working with me!
=> chore: update dev environment setup docs

schema/google/showcase/v1beta1/messaging.proto
Facilitates system tests in [gapic-generator-python](https://github.com/googleapis/gapic-generator-python/) on non-slash separated resource paths.
=> Move a non-slash resource path to the top of Blurb's patterns

server/services/identity_service.go, server/services/identity_service_test.go
The `UpdateUser` handler was returning the `UpdateUserRequest.User` value, rather than the actual updated `User` resource stored in the in-mem DB. This was unnoticed previously, because all fields were directly updated with the contents of `UpdateUserRequest.User`. With the addition of `proto3_optional`, we only want to update those optional fields that are **set**. Because the `UpdateUserRequest.User` was returned (instead of the newly updated resource), unset values appear as `nil` in the response. When compared with the `User` retrieved via `GetUser`, the comparison failed. This changes `UpdateUser` to return the _updated `User` resource_, not the incoming patch.
Furthermore, we need to use copies of data in tests rather than direct responses, because the server uses an in-memory …
=> Fix update user response

CHANGELOG.md, README.md, cmd/gapic-showcase/version.go, util/cmd/bump_version/main.go
Prepare a patch release that will pick #393 (and this commit) from `master` in order to avoid releasing non-slash resource names with this small fix.
=> release v0.10.1

schema/google/showcase/v1beta1/identity.proto, schema/google/showcase/v1beta1/messaging.proto
=> chore: remove _id suffix from resource name variables

.circleci/config.yml
Fixes #383. Since gapic-generator-typescript now supports proto3 `optional`, re-enabling it in CI.
=> test: test typescript in CI

.github/sync-repo-settings.yaml
The `push-generated-sources` job, which is part of our release system, was added as a required check. It isn't run on every PR.
=> chore: remove release job from required checks

.circleci/config.yml, util/genrest/genserver.go
fix: Change the mechanism for generated source detection to use `git-ls-files` rather than `git-diff`. This allows capturing files that are not yet tracked by git (via the flag `--other`)
fix: Remove timestamp from `genrest` to avoid needless commits.
=> feat: Add genrest to generated-source detection check

.circleci/config.yml
This was omitted in #479 
fix: Change the mechanism for change detection for `push-generated-source` to use `git-ls-files` rather than `git-diff`. This allows capturing files that are not yet tracked by git (via the flag `--other`)
=> chore: add genrest to push-generated-source change detection

util/cmd/protoc-gen-go_rest_server/main.go, util/genrest/genserver.go
The `genrest` protoc plug-in now depends on `google.golang.org/protobuf/compiler/protogen`, which provides a simpler
interface for implementing plug-ins.
More info:
- https://blog.golang.org/protobuf-apiv2
- https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/compiler/protogen
=> chore: Switch genrest plugin to use Go protobuf bindings v2

.circleci/config.yml
* make regen commit more conventional
* switch regen pr to reviewers from assignees
* switch alexander-fenster out for vchudnov-g
* remove prerelease setting on release creation
=> chore: make regen commit more conventional

cmd/gapic-showcase/endpoint.go, cmd/gapic-showcase/run.go, go.mod, util/genrest/genserver.go
This PR uses the cmux package to expose a single external port that selects incoming connections to route to the gRPC endpoint or the REST endpoint.
(ref: https://medium.com/@drgarcia1986/listen-grpc-and-http-requests-on-the-same-port-263c40cb45ff and https://github.com/soheilhy/cmux)
I define an Endpoint interface wrapping both the gRPC and the REST endpoints, as well as the cmux multiplexer that does the redirection. This infrastructure will also allow future endpoints to be easily added when we need them.
This also sets up the infrastructure for graceful shutdown upon receipt of a signal, though we are waiting for a PR in the cmux dependency for that to work fully. (The issue is described in https://github.com/soheilhy/cmux/pull/69#issuecomment-712928041.)
Implementation/review notes: …
=> feat: Serve gRPC and REST requests on the same external port

schema/google/showcase/v1beta1/messaging.proto
Using `-` character in the path templates directly violates [AIP-159](https://google.aip.dev/159). This change is just making things right and is non-breaking.
=> fix: use * in patterns instead of -

util/genrest/gomodel/gomodel.go, util/genrest/resttools/populatefield.go, util/genrest/resttools/populatefield_test.go
- We only accept the strings `"true"` and `"false"` now
- Also some minor cruft cleanup
(This reduces the `TODO` count by 2!)
=> fix(genrest): adopt strict JSON semantics for bool values

renovate.json
Scheduling update of googleapis to once per week, since it gets multiple commits per day and the protos depended upon by this project rarely change.
=> chore: throttle googleapis bazel dep update

util/compile_protos.go
With https://github.com/googleapis/gapic-generator-go/issues/514 fixed in generator version v0.17.2, we can remove this replacement script.
=> chore: remove metadata replacement script

.circleci/config.yml
I forgot to change the other version protoc in the CI config. This one is used for the regen job.
=> chore: update the other protoc in CI

cmd/gapic-showcase/endpoint.go, schema/google/showcase/v1beta1/showcase_v1beta1.yaml, server/services/iam_policy_service.go, server/services/iam_policy_service_test.go, server/services/locations_service.go, server/services/locations_service_test.go, server/services/services.go, util/cmd/release/main.go
Adds Location and IAMPolicy mix-in service gRPC implementations.
Adds an API Service configuration file with mix-in APIs and their `http.rules`.
=> feat: add location & iam mixin services

.github/workflows/release.yaml, cmd/gapic-showcase/run.go
Stop watching for `SIGSTOP` because windows libraries do not support this signal and the windows binary build fails. 
If we _really_ want to keep it for linux/macos, I can setup two lists in separate files with build tags for windows vs. non-windows but I don't think this is that important tbh. We don't even support `SIGCONT`, which is what follows `SIGSTOP` to "unpause" a process.
FIxes #603
=> chore: enable windows binary build

CHANGELOG.md, README.md, cmd/gapic-showcase/version.go, util/cmd/bump_version/main.go
Changes include:
- Add Compliance service for REGAPIC testing
- Add REGAPIC testing support with genrest
- Add mix-in service implementations
- Update API Service config with mix-ins and more
- Add Bazel proto_library targets for schema/
- Migrated to GitHub Actions
- Regen client & CLI with small updates
- Update dependencies
=> chore: draft v0.13.0 release

.github/workflows/release.yaml
Fixes #619 
The windows binary gets the `.exe` suffix causing the `tar` command targeting just `gapic-showcase` to fail, because it is actually `gapic-showcase.exe`.
=> chore: fix windows binary upload

go.sum, server/services/echo_service_test.go, server/services/messaging_service_test.go, server/services/operations_service_test.go, server/services/testing_service.go, server/services/testing_service_test.go
The `lint` job fails [here](https://github.com/googleapis/gapic-showcase/pull/626/checks?check_run_id=2006650208) on `go vet` because of some usage of `testing` APIs from none `testing` goroutines. This fixes that and some other minor linter warnings.
Also, this tidies the `go.sum`, which was going to be done in https://github.com/googleapis/gapic-showcase/pull/626 but that was blocked by these vet warnings. The vet warnings fix failed CI b.c the `go.sum` needed to be fixed. So this submits them together.
=> chore: fix go vet/lint warnings

util/compile_protos.go
There is an RPC named `Echo.Wait` that returns an LRO which creates a helper `WaitOperation` which is the same name as the RPC `Operations.WaitOperation` generated as a mixin method. This is a pretty one-off case as a method named `Wait` returning an LRO is not likely in an actual API. So we just rename the generated mixin method using `sed`  post generation.
=> chore: fix collision with operation helper

cmd/gapic-showcase/endpoint_test.go, util/genrest/goviewcreator.go, util/genrest/resttools/json.go
Also, replace deprecated `jsonpb` with `protojson` in genrest (`jsonpb` persists elsewhere in Showcase for now).
=> feat: Ensure full body responses from REST endpoints

cmd/gapic-showcase/compliance_suite_errors_test.go, cmd/gapic-showcase/compliance_suite_test.go, cmd/gapic-showcase/endpoint_test.go, util/genrest/goviewcreator.go, util/genrest/resttools/checkrestbody.go, util/genrest/resttools/checkrestbody_test.go, util/genrest/resttools/json.go, util/genrest/resttools/populatefield.go, util/genrest/resttools/populatefield_test.go
Showcase will return an error if any field name is not properly cased, as a way of enforcing that generators are strict in the format they emit.
Includes positive and negative tests.
=> Enforce lower-camel-cased field names in REST bodies and query params

RELEASING.md
- Added info on getting list of PRs since the last release
- Changed the tag release instructions to only push a single tag, which is safer and cleaner (I, for one, use many tags locally)
=> chore: Minor tweaks to RELEASING.md for helpfulness and safety.

cmd/gapic-showcase/compliance_suite_errors_test.go, util/genrest/goviewcreator.go, util/genrest/resttools/checkrequestformat.go, util/genrest/resttools/populatefield.go
This ensures we're correctly exercising the expected errors.
(And this caught some cases in negative tests where the errors generated were not the ones intended!)
=> chore: Add error identifiers and use them in tests

server/services/compliance_suite.json
Not strictly necessary, but this achieves consistency with how we expect generators to emit and ingest JSON bodies.
=> chore: Lower-camel-case field names in compliance_suite.json

.github/workflows/release.yaml
In order to capture multiline strings in `set-output` we need to escape the new line characters prior to providing it to `set-output`. I tested the commands to assign & parse the notes, but we will just have to see what happens with the Action on the next release.
Fixes #691
=> chore: fix multiline truncation of release notes

.github/workflows/ci.yaml
I thought I disabled this earlier, but I guess I didn't. I will roll any secrets in this repo again to be safe.
=> chore: disable codecov

util/genrest/resttools/checkrequestformat.go, util/genrest/resttools/checkrequestformat_test.go, util/genrest/resttools/headers.go
Showcase now requires incoming REST requests to have, in the header "x-goog-api-client", a token beginning with "rest/" and a token beginning with "gapic/"
This includes tests of this enforcement, and tighter (error-specific) tests for the content-encoding header enforcement as well.
=> feat: Require incoming REST requests to have correct x-goog-api-client header

cmd/gapic-showcase/endpoint.go
This was leading to Showcase integration tests failures in Python when upgrading to the latest Showcase release (https://github.com/googleapis/gapic-generator-python/pull/918), which pulled in cmux-using Showcase for the first time in that repo.
=> fix: Allow mTLS to work over gRPC using cmux.

cmd/gapic-showcase/compliance_suite_test.go, cmd/gapic-showcase/endpoint_test.go, schema/google/showcase/v1beta1/compliance.proto, server/services/compliance_service.go, server/services/compliance_service_test.go
This helps test, eg for` RepeatDataBodyInfo`, that top-level fields are
correctly encoded as query params. This is needed for testing REST for
GCE, which does *not* need to encode query params corresponding to
fields in nested sub-messages.
BREAKING CHANGE: This changes the structure (and hence wire format) of
the proto message `google.showcase.v1beta1.RepeatResponse`.
=> feat!: have compliance service respond with full request message

cmd/gapic-showcase/compliance_suite_test.go, cmd/gapic-showcase/endpoint_test.go, schema/google/showcase/v1beta1/compliance.proto, server/services/compliance_suite.json
This adds top-level scalar fields to compliance.proto:RepeatRequest to
ensure that they they are properly REST encoded, particularly as query
params.
=> feat: Test REST encoding of top-level scalar fields

util/genrest/goviewcreator.go, util/genrest/resttools/checkrequestformat.go, util/genrest/resttools/checkrequestformat_test.go
This returns an error response if GET or DELETE requests have a request body, or if we get a request that does not match any of the registered handlers.
=> feat: check invalid requests: bodies for GET or DELETE; unmatched requests

client/gapic_metadata.json, cmd/gapic-showcase/compliance_suite_test.go, schema/google/showcase/v1beta1/compliance.proto, server/services/compliance_service.go, server/services/compliance_service_test.go, server/services/compliance_suite.json
These methods are now exercised in `compliance_suite.json`.
Includes tests.
=> feat: add Compliance RPCs that transcode to PUT and PATCH HTTP verbs.

.github/sync-repo-settings.yaml, .github/workflows/ci.yaml
Disables the `typescript-smoke-test` job and removes it from the sync-repo-settings required checks.
=> chore: disable TS smoke test job

schema/google/showcase/v1beta1/echo.proto, server/services/echo_service.go, server/services/echo_service_test.go, util/compile_protos.go
This PR is in draft mode because it contains a hack in `compile_protos.go` to use a locally-built Go GAPIC generator protobuf plugin. Once the GAPIC generator is released with code to either ignore or support mapped paging responses, that hack can be removed.
=> feat: implement non-standard pagination returning maps of lists

schema/google/showcase/v1beta1/messaging.proto
BREAKING CHANGE: this changes the flattened method signature for the Messaging.SearchBlurbs() RPC to require  a `parent` parameter.
Without this change, the flattened method does not work, as the required field parent is not supplied.
=> fix!: add `parent` to method signature for `Messaging.SearchBlurbs()`

WORKSPACE.bazel, client/doc.go, client/echo_client.go, cmd/gapic-showcase/echo.go, go.mod, go.sum, schema/google/showcase/v1beta1/echo.proto, server/services/echo_service.go, server/services/echo_service_test.go
As part of supporting dynamic routing annotations per `google/api/routing.proto`, this adds the following:
1) Several sample routing annotations to the `Echo.Echo` method
2) The ability for each `Echo` service to echo the contents set with the `x-goog-request-params` metadata key to the response headers
An example of how to set and read the headers in Go:
```
func main() {
conn, err := grpc.Dial("localhost:7469", grpc.WithInsecure())
// This is what the generated client library should be creating
md := metadata.New(map[string]string{"x-goog-request-params": "testHeader"})
if err != nil {
log.Fatal(err)
}
defer conn.Close()
opt := option.WithGRPCConn(conn)
ctx := metadata.NewOutgoingContext(context.Background(), md)
echo, err := showcase.NewEchoClient(ctx, opt)
if err != nil { …
```
=> feat: add ability to echo headers & sample routing annotations on echo method

README.md, cmd/gapic-showcase/version.go, version.go
Also changes gapic-showcase versions in readme to `latest` where possible, and updates the documented min Go version to go1.16 which was already done.
=> chore: add version.go to embed version.txt

README.md
Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead. (https://go.dev/doc/go-get-install-deprecation)
=> chore: Update go command in Readme

.gitmodules
The pin is very old, does not seem to serve a visible purpose and it prevents having showcase dependencies e.g. `routing.proto` imported
=> chore: remove pin of api-common-protos

schema/google/showcase/v1beta1/BUILD.bazel
=> fix: add a routing.proto dependency to showcase proto bazel target

util/genrest/goviewcreator.go, util/genrest/resttools/error_response.go, util/genrest/resttools/error_response_test.go
This modifies the REST server generator to wrap errors in accordance with [Google Cloud's API Error format](https://cloud.google.com/apis/design/errors). Furthermore, it unpacks the gRPC status-based errors returned by the gRPC server handlers, and converts the gRPC Code into the proper HTTP status code.
Tested locally via Go generator REGAPIC integration tests.
=> feat(genrest): format rest errors as Google Errors

README.md
Add Java examples to README for talking to local showcase server with insecure channels.
=> chore: Add Java examples to README

.github/workflows/ci.yaml
`yoshi-code-bot` can't label its own PRs (e.g. with `automerge`), but we can use a follow up step using the GitHub action token to add the label. This is done in gapic-generator-go.
=> chore(ci): use github api for labeling

schema/google/showcase/v1beta1/identity.proto, schema/google/showcase/v1beta1/messaging.proto, util/genrest/gomodelcreator.go, util/genrest/resttools/populatefield.go, util/genrest/resttools/populatefield_test.go
Fixes the `google.api.http` `body` fields for UpdateUser, UpdateBlurb, and UpdateRoom to use the field in the request representing the resource, instead of `*`.
This also adds support for parsing some of the well known protobuf types that may be present as JSON encoded query parameters and that have special JSON encoding formats (see https://developers.google.com/protocol-buffers/docs/proto3#json). This API only makes use of Timestamp, Duration, and FieldMask.
=> fix!: use resource field in http body for Updates

util/genrest/goviewcreator.go
Fixes #1261 
Adding a conditional to generate an additional handler for PATCH requests:
i.e.
```
router.HandleFunc("/v1beta1/repeat:bodypatch", rest.HandleRepeatDataBodyPatch).Methods("PATCH")
router.HandleFunc("/v1beta1/repeat:bodypatch", rest.HandleRepeatDataBodyPatch).HeadersRegexp("X-HTTP-Method-Override", "^PATCH$").Methods("POST")
```
The second handler function matches specifically for Java's use case. It must match both conditions:
- Header- `X-HTTP-Method-Override: PATCH`
- Http Verb: `POST`
=> fix: Allow HTTP POST for PATCH RPCs

.github/workflows/assets.yaml
=> fix: build assets for darwin/arm64

util/compile_protos.go
Don't need the GAPIC snippets generated for showcase, so let's omit them.
=> chore: omit gapic snippetgen

util/genrest/goviewcreator.go, util/genrest/resttools/headers.go, util/genrest/resttools/populatefield.go, util/genrest/resttools/populatefield_test.go
Well-known type messages that JSON-encode to strings appear in URL paths and query params unquoted. When we extract them from these places, we need to quote them to make them valid JSON that we can pass to the JSON deserializer. We weren't doing the quoting previously.
Fixes #1263
=> fix(rest): properly handle string-encoded well-known types in URLs

server/services/sequence_service.go, server/services/sequence_service_test.go
Not sure what the difference between our environments was, perhaps the Go version used (gofmt can change between versions). Anyways here are the fixes @leahecole @galz10 
`gofmt -w ./server/services`
On my workstation, using Go:
`go version go1.21-20230317-RC01 cl/517508637 +f53a95fe39 linux/amd64`
On my laptop, using Go:
`go version go1.20.3 darwin/amd64`
=> chore: gofmt fixes

schema/google/showcase/v1beta1/sequence.proto, server/services/sequence_service.go
Currently, server streaming APIs do not resume from the point of failure. Before removing the contentSent property, the server would keep track of the last content that was sent before failing. To get closure to how server streams currently react to failure, we removed the contentSent property. This means that when we retry the request, the server will send the entire content, rather than starting from where it left off.
=> fix: remove content_sent from StreamingSequences

README.md
Enhance the README with an example of a Python connecting to a running Showcase server
=> docs(readme): add example of Python client connection (gRPC+REST)

schema/google/showcase/v1beta1/echo.proto, server/services/echo_service.go, server/services/echo_service_test.go
In the DIREGAPIC flow (`rest`-transport clients generated from synthetic protos emitted by  https://github.com/googleapis/disco-to-proto3-converter from public Discovery documents) currently used for the Google Compute Engine GAPIC, we only allow `google.protobuf.Any` types for fields whose paths end in `.error.details`. The actual types at run-time must be one of the types in `google/rpc/error_details.proto`. Since `error_details.proto` is not explicitly included in the synthetic GCE protos or the Showcase protos, we want to ensure that GAPICs in all languages can successfully decode these `error_details.proto` messages in a language-appropriate manner.
This change implements an RPC `EchoErrorDetails()` that adds such an `Any`-type field to the schema and return such an allowed …
=> feat: add EchoErrorDetails RPC returning error.details as field type google.protobuf.Any 

.github/workflows/ci.yaml, .gitmodules, README.md, util/cmd/release/main.go, util/compile_protos.go
https://github.com/googleapis/api-common-protos needs to be manually updated, so there is a 2-step process for `gapic-showcase` to pull in updated `api-common-protos`. By replacing the `api-common-protos` submodule with `googleapis`, it removes one of those steps.
=> feat: replace api-common-protos submodule with googleapis

schema/google/showcase/v1beta1/echo.proto, schema/google/showcase/v1beta1/showcase_v1beta1.yaml
Creating a new PR in place of https://github.com/googleapis/gapic-showcase/pull/1398/ that just contains the proto / service.yaml updates. 
This shows what the "happy path" configuration should look like for auto-population of the request_id for the Echo method on the Echo service .
=> feat: add autopopulated request id field to echo

.github/workflows/assets.yaml, util/cmd/release/main.go
- Update the release workflow to work on manual invocation in case the automated release process fails
- Updates the release script to copy all files from `googleapis/google/api` so that any new protos added into that directory are automatically pulled in. This creates some extra baggage (e.g. including proto files that aren't strictly needed), but removes the need for manual maintenance when a new proto gets added in that is needed.
=> chore: update release workflow to work on manual trigger

util/cmd/release/main.go
Follow up to https://github.com/googleapis/gapic-showcase/pull/1415
From https://github.com/googleapis/gapic-showcase/actions/runs/7491564937/job/20393070447 :
```
2024/01/11 16:21:36 cp: cannot stat 'schema/googleapis/google/api/*.proto': No such file or directory
```
shows the copying of the proto files wasn't working correctly as it wasn't recognizing the wildcard. This should hopefully fix that.
=> chore: fix globbing of wildcard protos in release script

.github/workflows/assets.yaml
...and another follow up to https://github.com/googleapis/gapic-showcase/pull/1416
https://github.com/googleapis/gapic-showcase/actions/runs/7491935131/job/20394310060#step:8:1 shows:
```
Run svenstaro/upload-release-action@v2
with:
repo_token: ***
file: ./dist/*
overwrite: true
file_glob: true
env:
TAG_NAME: v0.[3](https://github.com/googleapis/gapic-showcase/actions/runs/7491935131/job/20394310060#step:8:3)0.0
Error: Input required and not supplied: tag
```
This updates the workflow to use either the event tag or the manually supplied tag.
=> chore: update assets.yaml for manual invocation

.github/workflows/assets.yaml
and another follow up to: https://github.com/googleapis/gapic-showcase/pull/1417
From: https://github.com/googleapis/gapic-showcase/actions/runs/7492920153/job/20397491734#step:7:12
```
Run go run ./util/cmd/release -version=0.30.0
2024/01/11 18:22:15 google/api/launch_stage.proto: File not found.
google/api/client.proto:19:1: Import "google/api/launch_stage.proto" was not found or had errors.
google/api/client.proto:121:3: "LaunchStage" is not defined.
google/showcase/v1beta1/compliance.proto:1[8](https://github.com/googleapis/gapic-showcase/actions/runs/7492920153/job/20397491734#step:7:9):1: Import "google/api/client.proto" was not found or had errors.
exit status 1
Error: Process completed with exit code 1.
```
I think what's happening is that since it's checking out the version of …
=> chore: update workflow to run from main temporarily

.github/workflows/assets.yaml
From: https://github.com/googleapis/gapic-showcase/actions/runs/7493151012/job/20398247464
```
Run actions/upload-release-asset@v1
Error: Input required and not supplied: upload_url
```
We need to supply the `upload_url` for manual invocation of the workflow. This attempts to fix that.
=> chore: Update Github upload_url in workflow

.github/workflows/assets.yaml
Follow up to https://github.com/googleapis/gapic-showcase/pull/1425
Upon reading https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs more closely, I am setting the outputs from `get-upload-url` as environment variable before using them instead of using them directly.
=> chore: fix workflow upload url

.github/workflows/assets.yaml
From: https://github.com/googleapis/gapic-showcase/actions/runs/7506233217
Getting an invalid syntax error:
```
[Invalid workflow file: .github/workflows/assets.yaml#L92](https://github.com/googleapis/gapic-showcase/actions/runs/7506233217/workflow)
The workflow is not valid. .github/workflows/assets.yaml (Line: 92, Col: 14): Unrecognized named-value: 'AUTO_UPLOAD_URL'. Located at position 1 within expression: AUTO_UPLOAD_URL
```
Moving the `env` piece to be under the job instead of under `steps` to see if that resolves the issue.
=> chore: move env under job instead of steps

schema/google/showcase/v1beta1/echo.proto, server/services/echo_service.go
To make it easier to check what request ID is sent as part of the request, this PR adds it to EchoResponse so tests can check the response directly.
=> feat: add request id as part of EchoResponse

schema/google/showcase/v1beta1/echo.proto, schema/google/showcase/v1beta1/showcase_v1beta1.yaml, server/services/echo_service.go
To test the `The field supports explicit presence, and has not been set by the user` requirement of [AIP-4235](https://google.aip.dev/client-libraries/4235)
```
The field must be automatically populated if and only if one of the following conditions holds:
The field supports explicit presence, and has not been set by the user
The field doesn't support explicit presence, and its value is the empty string (i.e. the default value)
```
=> feat: Add autopopulated proto3 optional field to echo

.github/CODEOWNERS
Switch from `actools` to `core-client-libraries`, which is the latest, up-to-date GitHub Team.
=> chore: make core-client-libraries CODEOWNERS

renovate.json
Protobuf v26 has some breaking changes and in general we need to wait to take it, so let's pause updating it for the time being.
=> chore(deps): stop bazel protobuf updates

server/services/echo_service.go, server/services/echo_service_test.go, server/services/sequence_service_test.go
Fixes https://github.com/googleapis/gapic-showcase/issues/1499
=> test: fix tests for headers and trailers

util/genrest/goviewcreator.go, util/genrest/resttools/headers.go
Towards #1493, but note that this will occur for all Showcase services, not just `Echo`. 
This can be verified manually on the shell via:
```
❯ curl -i -X POST -H "X-Goog-Api-Client: rest/0.0.0 gapic/0.0.0" -H 'Content-Type: application/json' http://localhost:7469/v1beta1/echo:echo -d'{"content":"g
reetings"}'                                                                                                                                                 
HTTP/1.1 200 OK
X-Showcase-Request-Accept: */*
X-Showcase-Request-Content-Length: 23
X-Showcase-Request-Content-Type: application/json
X-Showcase-Request-User-Agent: curl/8.5.0
X-Showcase-Request-X-Goog-Api-Client: rest/0.0.0 gapic/0.0.0
Date: Fri, 26 Apr 2024 21:33:24 GMT
Content-Length: 104
Content-Type: text/plain; charset=utf-8
{ …
```
=> feat(server): echo request headers in response over REST transport

cmd/gapic-showcase/compliance_suite_errors_test.go, cmd/gapic-showcase/compliance_suite_test.go, cmd/gapic-showcase/endpoint.go, cmd/gapic-showcase/endpoint_test.go, util/compile_protos.go, util/genrest/goviewcreator_test.go, util/genrest/protomodelcreator.go, util/genrest/resttools/checkrequestformat.go
Fixes https://github.com/googleapis/gapic-showcase/issues/1526
=> chore(cmd,util): replace use of io/ioutil

cmd/gapic-showcase/endpoint.go, server/services/echo_service.go, server/services/iam_policy_service.go, server/services/iam_policy_service_test.go, server/services/messaging_service.go, server/services/operations_service.go, server/services/operations_service_test.go, server/services/services.go, server/services/test_common.go, server/waiter.go, server/waiter_test.go
Replace use of google.golang.org/genproto/googleapis/iam/v1 with cloud.google.com/go/iam/apiv1/iampb #1528.
Fixes #1528
=> chore(cmd,server): replace use of google.golang.org/genproto/googleapis/iam/v1

server/services/services.go
Replace use of google.golang.org/genproto/googleapis/longrunning with cloud.google.com/go/longrunning/autogen/longrunningpb.
Fixes #1527
=> chore(cmd,server): replace use of google.golang.org/genproto/googleapis/longrunning

cmd/gapic-showcase/gapic-showcase.go, server/services/echo_service_test.go, server/services/iam_policy_service.go, server/services/identity_service.go, server/services/identity_service_test.go, server/services/messaging_service.go, server/services/messaging_service_test.go, server/services/operations_service.go, server/services/operations_service_test.go, server/services/testing_service_test.go, server/session_test.go, server/spec/v1/unary.go, server/spec/v1/unary_test.go, server/waiter.go, server/waiter_test.go, util/genrest/internal/pbinfo/pbinfo.go
=> chore(cmd,server,util): replace use of github.com/golang/protobuf/proto

cmd/gapic-showcase/gapic-showcase.go, server/services/echo_service_test.go, server/services/iam_policy_service.go, server/services/identity_service.go, server/services/identity_service_test.go, server/services/messaging_service.go, server/services/messaging_service_test.go, server/services/operations_service.go, server/services/operations_service_test.go, server/services/testing_service_test.go, server/session_test.go, server/spec/v1/unary.go, server/spec/v1/unary_test.go, server/waiter.go, server/waiter_test.go, util/genrest/internal/pbinfo/pbinfo.go
This reverts commit b9f8777913ed19a4c6de375857364133a92c63f7. This was breaking `go build`
=> fix: revert "replace use of github.com/golang/protobuf/proto (#1534)"

.github/workflows/ci.yaml
This would have caught some previous build failures that were not caught by simply running the tests.
=> chore(ci): run go build

server/services/echo_service_test.go, server/services/iam_policy_service.go, server/services/identity_service.go, server/services/identity_service_test.go, server/services/messaging_service.go, server/services/messaging_service_test.go, server/services/operations_service.go, server/services/operations_service_test.go, server/services/testing_service_test.go, server/session_test.go, server/spec/v1/unary.go, server/spec/v1/unary_test.go, server/waiter.go, server/waiter_test.go, util/genrest/internal/pbinfo/pbinfo.go
This is basically b9f8777 but removing changes that were from generated files.
Updates: #1525
=> fix: replace use of github.com/golang/protobuf/proto where possible

.github/workflows/ci.yaml
This is useful for debugging CI/build issues. Motivated by #1577.
=> chore: allow workflow_dispatch on ci.yaml action

util/cmd/release/main.go
This should fix the "proto-assets" step in the "assets" action (eg for [this failing action](https://github.com/googleapis/gapic-showcase/actions/runs/14498515142/job/40672303266))
=> build: include code.proto in the release steps

.github/workflows/assets.yaml
Refs:
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
- https://github.com/svenstaro/upload-release-action?tab=readme-ov-file#permissions
=> build: fix assets action by fixing GitHub token access
